module Categories

    struct category
        name
        lccs_classes::Array
        float::Float64
    end

    categories=[
        category(
            "rainforest",
            [
                "tree_broadleaved_evergreen_closed_to_open",
                "tree_cover_flooded_fresh_or_brakish_water"
            ],
            0.0
        ),
        category(
            "forest",
            [
                "tree_broadleaved_deciduous_closed_to_open",
                "tree_broadleaved_deciduous_closed",
                "tree_broadleaved_deciduous_open",
                "tree_needleleaved_evergreen_closed_to_open",
                "tree_needleleaved_evergreen_closed",
                "tree_needleleaved_evergreen_open",
                "tree_needleleaved_deciduous_closed_to_open",
                "tree_needleleaved_deciduous_closed",
                "tree_needleleaved_deciduous_open",
                "tree_mixed",
                "tree_cover_flooded_saline_water",
            ],
            0.1
        ),
        category(
            "shrubland",
            [
                "shrubland",
                "shrubland_evergreen",
                "shrubland_deciduous",
                "shrub_or_herbaceous_cover_flooded",
            ],
            0.2
        ),
        category(
            "flat_vegetation",
            [
                "grassland",
                "lichens_and_mosses",
            ],
            0.3
        ),
        category(
            "sparse_vegetation",
            [
                "mosaic_natural_vegetation",
                "mosaic_tree_and_shrub", 
                "mosaic_herbaceous", 
                "sparse_vegetation",
                "sparse_tree",
                "sparse_shrub",
                "sparse_herbaceous",
            ],
            0.4
        ),
        category(
            "no_data",
            [
                "no_data"
            ],
            0.5
        ),
        category(
            "water",
            [
                "water",
                "snow_and_ice"
            ],
            0.7
        ),
        category(
            "bare_areas",
            [
                "bare_areas",
                "bare_areas_consolidated",
                "bare_areas_unconsolidated",
            ],
            0.8
        ),
        category(
            "cropland",
            [
                "cropland_rainfed", 
                "cropland_rainfed_herbaceous_cover", 
                "cropland_rainfed_tree_or_shrub_cover",
                "cropland_irrigated",
                "mosaic_cropland"
            ],
            0.9
        ),
        category(
            "urban",
            [
                "urban"
            ],
            1.0
        )
    ]

end